source 'https://rubygems.org'

group :test do
  gem 'rspec', '~> 3.5.0'
  gem 'rspec-mocks', '~> 3.5.0'
  gem 'simplecov', '~> 0.12.0', require: false
  gem 'rubocop', require: false # for Atom editor
end

# https://github.com/pry/pry
# http://pryrepl.org
gem 'pry', '~> 0.10.4'
